[config]
default_to_workspace = false

[tasks.update]
args = ["update"]
command = "cargo"
install_crate = "cargo-edit"

[tasks.upgrade]
args = ["upgrade"]
command = "cargo"
install_crate = "cargo-edit"

[tasks.update-all]
dependencies = ["update", "upgrade"]
script = '''
cd util/gen-syntax
makers update-all
'''

[tasks.coverage]
args = ["llvm-cov", "--workspace", "--all-features", "--html", "--open", "--ignore-filename-regex", "\".cargo|.*_test\\.rs\""]
clear = true
command = "cargo"
install_crate = "cargo-llvm-cov"
